### ISSUE TITLE
Create simple HTML/CSS scaffold for Phase 1

### ISSUE THREAD

**Issue by fwenzel** [mozilla/apps-design#1]
This Issue is for the developer to make a simple HTML/CSS page that we can drop the content into.

@carolw will you share the overview that you showed this week (i.e., "a list different patterns, possible to jump between design pattern and the corresponding x-tag") it's easier to determine what this simple site needs to look like?

**Comment by carolw** [comment]
A sketch of the simple site (independent design and code sites with links to each other)
https://www.dropbox.com/s/280tndsqibo3m5m/dev%20ecosystem%20design%20site%20concept.pdf

**Comment by carolw** [comment]
2nd sketch
https://www.dropbox.com/s/q0bbx5uooougbkq/apps%20design%20site%20sketch%20.pdf

design guideline content outline:
https://etherpad.mozilla.org/apps-design-outline
