### ISSUE TITLE
Develop additional x-tags based on list of design elements

### ISSUE THREAD

**Issue by carolw** [mozilla/apps-design#5]
caroline will specify specs for the list of design elements & work with developer to develop additional x-tags

**Comment by fwenzel** [comment]
_poke_ @pennyfx (Arron) as an early heads-up

**Comment by carolw** [comment]
@pennyfx 1st draft of the additional x-tags is here. Please feel free to comment!
https://etherpad.mozilla.org/design-dev-ecosystem-xtag

(No specs yet. I will write the specs once we have the chance to go over the list.)

**Comment by fwenzel** [comment]
thanks @carolw, looking good! @ednapiranha, want to take a look on Monday?

**Comment by carolw** [comment]
caroline will specify specs for the following list:

*Structural
-plain list
-grid list

*notification
-dialog: toast/roar
-dialog: popup

*inputs
-search
-slider
-toggle switch
-time/date picker
-rating

*navigation
-drop-down menu
-index scroller
